apiVersion: v1
kind: Service
metadata:
  name: redmine
  namespace: redmine
  labels:
    app: redmine
spec:
  type: NodePort
  selector:
    app: redmine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32000
